### ISSUE TITLE
Call to Metric.Config never returns

### ISSUE THREAD

**Issue by shawnarvin** [Recognos/Metrics.NET#45] opened 2016-11-22 20:41 UTC
Hi,
I am using Metrics.NET v0.3.7 with Nancy.Metrics v0.3.7 and Nancy v1.4.3. In my bootstrapper the following call to Metric.Config never returns:

                Metric.Config
                    .WithAllCounters()
                .WithReporting(r => r.WithConsoleReport(TimeSpan.FromSeconds(30)))
                .WithNancy(pipelines) ;

There are no indication of any errors. Any Idea what might be the issue?

Thank you.

**Comment by PaulParau** [comment] 2016-11-23 16:31
Hi,

I've looked into it and wasn't able to reproduce the issue. We're actively using Nancy.Metrics v.0.3.7 and Nancy 1.4.3 in various environments and it works (admittedly with Metrics.NET v.0.4.1-pre). I've tried downgrading Metrics.NET to v0.3.7 and it still works. I've also tried to reproduce the error in the NancyFx.Sample project here in the repo & it works as well.

Is it possible for you to determine which of the chained extension methods hangs?

**Comment by shawnarvin** [comment] 2016-11-23 18:34
Thank you for taking the time to look into this. Once I removed the call to "WithAllCounter()" ,things seems to be working. Surprisingly the metrics route also works without this call, so I am not sure if it was needed at all or there is some data that is not getting collected. I am still getting familiar with this tool but haven't seen any negative effects by not call this method. The metrics route looks awesome.

**Comment by shawnarvin** [comment] 2016-11-23 18:41
One thing I forgot to mention is that I am using .NET framework 4.6.1.

**Comment by Liwoj** [comment] 2016-11-30 09:35
Hi

My guess is the problem is in "WithAllCounters()" call (as you found yourself). Call just creates some metrics based on Windows performance counters.
It seems performance counters API is very unreliable. Reading them can hang your app forever for example (see [here ](https://groups.google.com/forum/#!searchin/ravendb/performance$20counters/ravendb/10hNdY66JWQ/I5VDJSgImOgJ) or [here](https://github.com/SignalR/SignalR/pull/1572)). I'v observed this behavior more than once myself. Just avoid them...

@PaulParau There is quite few issues already around performance counters. Probably good idea would be to remove "WithAllCounters()" from examples and put some note to XML comment...

**Comment by PaulParau** [comment] 2016-12-01 12:09
@Liwoj you're probably right. There's also the related issue #10, will do something about it in the near future.

**Comment by PaulParau** [comment] 2016-12-23 21:43
Since this is most probably an issue with the performance counters API, there's not much we can do about it besides what we have done for #10, so I'm closing this issue.

**Closed by PaulParau** 2016-12-23 21:43 UTC
